# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Viralget
email: till@tillcarlos.com
author: Till Carlos
description: > # "Viralget help you to run viral campaigns. 
  Give you freebies, books, movies... anything you want to 
  trade for subscribers. With Viralget you have the 
  full power over the design of your campaign."
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/maerketing1
